### ISSUE TITLE
レビュー感想 [こす]

### ISSUE THREAD

**Issue by kosu27** [emi-h/my-portfolio#3]
[感想]
Apollo綺麗に実装されていました！
ディレクトリ構造が自分とは異なっていて、とても学びになりました🙇‍♂️

[レビュー]
・Twitterとgithub配下にあるボタンが少しずれていたので、統一できると綺麗になると思います。
・僕もそうなんですけど、GitHubの言語の表示順がGitHubと異なっている所。
Javascriptが何故か先に来ちゃうんですよね...自分も色々試してみます！わかったら共有しますね！
・動作確認は問題なく、実装出来ていました👍
・libsのフォルダは一般的にはlibフォルダで書かれているのが多く見られるので、libに直した方が良いかな？と感じました。

確認よろしくお願い致します！

**Comment by emi-h** [comment]
レビューありがとうございました！

> ・Twitterとgithub配下にあるボタンが少しずれていたので、統一できると綺麗になると思います。

　→両セクションの高さを合わせて、はみ出るTwitterはスクロールさせました！

> ・僕もそうなんですけど、GitHubの言語の表示順がGitHubと異なっている所。

　→こちらクエリの変更で対応できました！（サイズ順に言語を取得する）
　下記ファイルの20行目です。
　[https://github.com/emi-h/my-portfolio/blob/GithubApi/src/pages/api/github.ts](https://github.com/emi-h/my-portfolio/blob/GithubApi/src/pages/api/github.ts)

> ・libsのフォルダは一般的にはlibフォルダで書かれているのが多く見られるので、libに直した方が良いかな？と感じました。

　→変更しました！
